package com.crm.dto;


public class TransactionDto {
	private int id;//This id is generated by database
	private String department;
	private long date;
	private String orderCode;//This is transaction id
	private String goodsId;
	private int count;
	private double total;
	private String memberId;
	
	
	public TransactionDto(String memberId, String department, long date, String orderCode, String goodsId, int count, double total){
		this.department = department;
	    this.date = date;
	    this.memberId = memberId;
	    this.orderCode = orderCode;
	    this.goodsId = goodsId;
	    this.count = count;
	    this.total = total;
	}
	
	public TransactionDto(int id, String memberId, String department, long date, String orderCode, String goodsId, int count, double total){
		this.id = id;
		this.memberId = memberId;
		this.department = department;
	    this.date = date;
	    this.orderCode = orderCode;
	    this.goodsId = goodsId;
	    this.count = count;
	    this.total = total;
	}
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	public long getDate() {
		return date;
	}
	public void setDate(long date) {
		this.date = date;
	}
	public String getOrderCode() {
		return orderCode;
	}
	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}
	public String getGoodsId() {
		return goodsId;
	}
	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}
	
	public double getTotal() {
		return total;
	}
	public void setTotal(double total) {
		this.total = total;
	}

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public String getMemberId() {
		return memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}
	

}
